version: "3.8"
services:
  pg_dump_data:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./dumps:/dumps
      - ./scripts:/scripts
    command:
      [
        "bash",
        "-c",
        "pg_dump -T '_prisma_migrations' -a -Fc -v --no-owner -d $$DATABASE_URL -f /dumps/dump_file_name",
      ]

  pg_restore_data:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./dumps:/dumps
      - ./scripts:/scripts
    command:
      [
        "bash",
        "-c",
        "pg_restore -a -v -O -d $$DATABASE_URL_DEST /dumps/dump_file_name",
      ]
