version: "3.8"
services:
  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dfda_test
    ports:
      - "5433:5432"
    container_name: dfda-postgres
    volumes:
      - .postgres:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"

volumes:
  redis_data: