# fly.toml app configuration file generated for web-thrumming-brook-1822 on 2025-01-21T15:34:48-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'decentralized-fda-web'
primary_region = 'iad'

[build]

[deploy]
  release_command = 'npx prisma migrate deploy'
  seed_command = 'ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts'

[http_service]
  internal_port = 3000
  force_https = true
  tls_min_version = "1.2"
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.logging]
    level = "info"
    filter = "exclude:PHI"

[backups]
  enabled = true
  schedule = "daily"
  retention = "30d"

[monitoring]
  enabled = true
  alert_email = "devops@dfda.earth"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  [vm.security]
    isolation = "strict"
    encrypted_volumes = true
