# Production environment - HIPAA compliant
app = "dfda-prod"
primary_region = "ord"

[build]
  image = "dfda:prod"

[env]
  NODE_ENV = "production"

[http_service]
  internal_port = 3000
  force_https = true
  tls_min_version = "1.2"
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']
  [http_service.logging]
    level = "info"
    filter = "exclude:PHI"

[deploy]
  release_command = 'npx prisma migrate deploy'
  seed_command = 'ts-node --compiler-options {"module":"CommonJS"} prisma/seed.ts'

[backups]
  enabled = true
  schedule = "daily"
  retention = "30d"

[monitoring]
  enabled = true
  alert_email = "devops@dfda.earth"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  [vm.security]
    isolation = "strict"
    encrypted_volumes = true

[services.concurrency]
  hard_limit = 25
  soft_limit = 20 