# --- cloudbuild.yaml ---
steps:
  # Build Step (Modified)
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/${PROJECT_ID}/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - apps/dfda-node # Build context directory
      - '-f'
      - apps/dfda-node/Dockerfile # Dockerfile location relative to context
    id: Build
    # Make DOPPLER_TOKEN available to this build step's environment
    secretEnv: ['DOPPLER_TOKEN']

  # Push Step (Unchanged)
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/${PROJECT_ID}/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push

  # Deploy Step (Unchanged)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - '--platform=managed'
      - >-
        --image=$_AR_HOSTNAME/${PROJECT_ID}/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud

# Define the secret to be made available
availableSecrets:
  secretManager:
  - versionName: projects/${PROJECT_ID}/secrets/GCP_SUPABASE_DOPPLER_TOKEN/versions/latest # Use default PROJECT_ID and correct secret name
    env: 'DOPPLER_TOKEN' # Maps the secret value to this environment variable name

images:
  - >-
    $_AR_HOSTNAME/${PROJECT_ID}/$_AR_REPOSITORY/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  # _PLATFORM: managed # Usually set by trigger or default
  _SERVICE_NAME: fda-gov-v2
  _TRIGGER_ID: 8ab3f933-6491-45d3-8227-ab9f037314de # Default value, likely overridden by trigger
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _AR_REPOSITORY: cloud-run-source-deploy
  # REPO_NAME and COMMIT_SHA are usually provided by the trigger
  # Add defaults if needed for manual runs:
  # REPO_NAME: 'your-repo-name'
  # COMMIT_SHA: 'latest'
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - fda-gov-v2 