version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fda_gov_v2_db
    ports:
      - "5435:5432"  # Using 5435 instead of default 5432 to avoid conflicts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fda_gov_v2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  mailhog:
    image: mailhog/mailhog
    container_name: fda_gov_v2_mail
    ports:
      - "1025:1025"  # SMTP server port
      - "8025:8025"  # Web interface port
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - mailhog_data:/tmp

volumes:
  postgres_data:
    name: fda_gov_v2_postgres_data
  mailhog_data:
    name: fda_gov_v2_mailhog_data 