name: Deploy to AWS Lightsail Container Service

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  LIGHTSAIL_SERVICE_NAME: ${{ secrets.LIGHTSAIL_SERVICE_NAME }}
  DOPPLER_TOKEN: ${{ secrets.DOPPLER_TOKEN }}
  DOPPLER_PROJECT: ${{ secrets.DOPPLER_PROJECT }}
  DOPPLER_CONFIG: ${{ secrets.DOPPLER_CONFIG }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build and push container using custom script
      - name: Build and push container
        run: npx ts-node apps/web/scripts/build-and-push-container.ts

      # Deploy to Lightsail using custom script
      - name: Deploy to Lightsail
        run: npx ts-node apps/web/scripts/deploy-lightsail.ts
