name: Integration Tests

on:
  # Run on all pushes
  push:
  # Run on all PRs
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9.15.3
          run_install: false
          
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
            
      - name: Install dependencies
        run: |
          pnpm install --frozen-lockfile
          pnpm -F dfda install --frozen-lockfile
            
      # Setup environment variables
      - name: Setup environment variables
        working-directory: apps/web
        run: cp .env.example .env

      # Start database and other services
      - name: Start Docker services
        working-directory: apps/web
        run: |
          docker-compose up -d db
          echo "Waiting for database to be ready..."
          timeout 30 bash -c 'until docker exec dfda-postgres pg_isready; do sleep 2; done' || false
            
      # Build and test web app
      - name: Build and test web app
        working-directory: apps/web
        run: |
          pnpm run build
          pnpm start &
          echo "Waiting for Next.js to be ready..."
          timeout 30 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' localhost:3000)" != "200" ]]; do sleep 2; done' || false
          pnpm test:integration
        env:
          CI: true
          DATABASE_URL: postgresql://user:pass@localhost:5433/dfda_test

      # Optional: Upload test results as artifacts
      - name: Upload test results
        if: always() && (hashFiles('apps/web/coverage/**') != '' || hashFiles('apps/web/test-results/**') != '' || hashFiles('apps/web/**/junit.xml') != '')
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            apps/web/coverage/
            apps/web/test-results/
            apps/web/**/junit.xml
          retention-days: 30 